#!/bin/bash
printf "\n\n### Reverse ### \n\n"
exec 2>&1  # redirect stderr to stdout: https://unix.stackexchange.com/q/505581/16569

# A function that echoes and executes a command.
call() { 
	echo "! ${@/eval/}" 
	$@
}

call make --silent -f Makefile clean
call make -f Makefile a.out
ERROR=$?
if [ $ERROR -ne 0 ]
then 
	printf "\n*** Error code: $ERROR ***\n"
	printf "\n*** Grade: 0 ***\n"
else
    call timeout 1 ./a.out
	ERROR=$?
	if [ $ERROR -ne 0 ]
	then
		printf "\n*** Error code: $ERROR ***\n"
		printf "\n*** Grade: 0 ***\n"
	fi
fi

make --silent -f Makefile clean
