#!/bin/bash 
echo "*** Grade exercise ***" 
 
echo "javac *.java" 
javac *.java 
 
let total=2
let sum=0 
 
INPUT=`cat input-1.io` 
OUTPUT=`java EX01 $INPUT` 
EXPECTED=`cat output-1.io` 
echo output: $OUTPUT 
if [ "$OUTPUT" == "$EXPECTED" ]; then 
let sum++ 
fi 
 
INPUT=`cat input-2.io` 
OUTPUT=`java EX01 $INPUT` 
EXPECTED=`cat output-2.io` 
echo output: $OUTPUT 
if [ "$OUTPUT" == "$EXPECTED" ]; then 
let sum++ 
fi 
 
let "wrong = total - sum" 
echo "Correct: $sum, Wrong: $wrong" 
let "grade = sum / total * 100" 
echo "*** Grade: $grade% ***"