#!/bin/bash

HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "! make"
make

echo "! run on inputs"

let right=0
let wrong=0

OUTPUT=`./main.exe < $HERE/1-input`
EXPECTED=`cat $HERE/1-output`
echo "Input 1: your output=$OUTPUT, expected output=$EXPECTED"
if [ "$OUTPUT" == "$EXPECTED" ]; then
    let right++
else
    let wrong++
fi

OUTPUT=`./main.exe < $HERE/2-input`
EXPECTED=`cat $HERE/2-output`
echo "Input 2: your output=$OUTPUT, expected output=$EXPECTED"
if [ "$OUTPUT" == "$EXPECTED" ]; then
    let right++
else
    let wrong++
fi

let "grade = right * 100 / (right + wrong)"
echo "*** Right: $right. Wrong: $wrong. Grade: $grade% *** "
